// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHM5pox9b3UqA63D1MwGbMBiA5oMXVzk',
    appId: '1:295596573405:web:33619e7f35b44515c11134',
    messagingSenderId: '295596573405',
    projectId: 'know-your-meal-4c764',
    authDomain: 'know-your-meal-4c764.firebaseapp.com',
    storageBucket: 'know-your-meal-4c764.firebasestorage.app',
    measurementId: 'G-NVF9T0XERW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAILaJRZc6WnrQ01lueBMLW6YOM23Rsd6U',
    appId: '1:295596573405:android:faec13594c26e9f2c11134',
    messagingSenderId: '295596573405',
    projectId: 'know-your-meal-4c764',
    storageBucket: 'know-your-meal-4c764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9vv_kDfFApIvjs80SofzLISm4rwoGFy4',
    appId: '1:295596573405:ios:5f5f9e4266ebd4e5c11134',
    messagingSenderId: '295596573405',
    projectId: 'know-your-meal-4c764',
    storageBucket: 'know-your-meal-4c764.firebasestorage.app',
    iosBundleId: 'com.example.knowYourMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9vv_kDfFApIvjs80SofzLISm4rwoGFy4',
    appId: '1:295596573405:ios:5f5f9e4266ebd4e5c11134',
    messagingSenderId: '295596573405',
    projectId: 'know-your-meal-4c764',
    storageBucket: 'know-your-meal-4c764.firebasestorage.app',
    iosBundleId: 'com.example.knowYourMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHHM5pox9b3UqA63D1MwGbMBiA5oMXVzk',
    appId: '1:295596573405:web:7b9cc099bcc2d784c11134',
    messagingSenderId: '295596573405',
    projectId: 'know-your-meal-4c764',
    authDomain: 'know-your-meal-4c764.firebaseapp.com',
    storageBucket: 'know-your-meal-4c764.firebasestorage.app',
    measurementId: 'G-0TQ8NVD89B',
  );
}
